### ISSUE TITLE
archive this repo

### ISSUE THREAD

**Issue by marcoieni** [stevenguh/spacecode#11]
When the migration to [VSpaceCode](https://github.com/VSpaceCode/VSpaceCode/) is finished, this repo should be archived and there should be a link to the new repo in the README.

**Comment by stevenguh** [comment]
This repo will be archived once `v0.4.0` is release on `VSpaceCode` so I can close the other issue on this repo.

**Comment by stevenguh** [comment]
`v0.4.0` is released on `VSpaceCode`. Closing this issue.
