### ISSUE TITLE
README: explain better how to customize key bindings

### ISSUE THREAD

**Issue by marcoieni** [stevenguh/spacecode#5]
I followed this instruction from the readme:

> To customize the menu, copy the default spacecode.bindings value in package.json in this repo and put the updated spacecode.bindings config in your own setting.json.

When I copy spacecode.bindings I get the following error:
![image](https://user-images.githubusercontent.com/11428655/82735495-7c6a1f80-9d22-11ea-9a34-aebe14f7798b.png)

Instead something like this works:
```
{
   "spacecode.bindings":[
      {
         "key":"f",
         "name":"File...",
         "type":"bindings",
         "bindings":[
            {
               "key":"f",
               "name":"Open file",
               "type":"command",
               "command":"workbench.action.files.openFileFolder"
            },
            {
               "key":"i",
               "name":"Indentation...",
               "type":"bindings",
               "bindings":[
                  {
                     "key":"i",
                     "name":"Change indentation",
                     "type":"command",
                     "command":"changeEditorIndentation"
                  },
                  {
                     "key":"d",
                     "name":"Detect indentation",
                     "type":"command",
                     "command":"editor.action.detectIndentation"
                  }
               ]
            }
         ]
      }
   ]
}
```

**Comment by stevenguh** [comment]
Thanks for letting me know about the confusion. I will change the way I explain it :) Just want to make sure, you are able to customize it, right?

**Comment by marcoieni** [comment]
Sure! :rocket:

**Comment by stevenguh** [comment]
@MarcoIeni Just updated the README. Let me know if it is clearer 😊

**Comment by marcoieni** [comment]
It looks clear to me, thanks!
