### ISSUE TITLE
double space does not work

### ISSUE THREAD

**Issue by TungLamC** [stevenguh/spacecode#6]
I try to get double space to execute command "workbench.action.showCommands" like this
![image](https://user-images.githubusercontent.com/29020158/83476892-6ac40d00-a4c4-11ea-815c-96420669539a.png)
It do appear in my quickOpenList,but it doesn't work when I press space and space like spacemacs
![image](https://user-images.githubusercontent.com/29020158/83476976-a232b980-a4c4-11ea-8526-c54ff8c3ab58.png)

**Comment by stevenguh** [comment]
It should work if you use space character instead. However, the key for that menu item would be invisible. Maybe this issue can used to track that to display `SPC` in the menu if space character is used as key.

**Comment by TungLamC** [comment]
@stevenguh 
You mean use space character in "key" like this?
![image](https://user-images.githubusercontent.com/29020158/83478438-6568c180-a4c8-11ea-89bf-f2a988338cb9.png)
Unfortunately, It still doesn't work, after I press space button, It just input a space character in my input box.
![image](https://user-images.githubusercontent.com/29020158/83478617-df994600-a4c8-11ea-8871-af78f10d89ff.png)

**Comment by stevenguh** [comment]
Sorry for not being more specific. Something like this:
```json
"spacecode.bindings: [
    "key": " ",
    "name": "show commands",
    "type": "command",
    "command": "workbench.action.showCommands"
]
```

**Comment by TungLamC** [comment]
It work for me!
![image](https://user-images.githubusercontent.com/29020158/83478779-4cacdb80-a4c9-11ea-9ce1-4397ed858b33.png)
And as you said the item is invisible,but it doesn't matter for me.Thanks for the nice extension.🧐
